<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Talvora.Tray</AssemblyName>
    <RootNamespace>Talvora.Tray</RootNamespace>
    <ApplicationIcon>..\..\assets\Talvora.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Talvora.Shared\Talvora.Shared.csproj" />
  </ItemGroup>
</Project>
