<Project Sdk="MSTest.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Talvora.Abstractions/Talvora.Abstractions.csproj" />
    <ProjectReference Include="../../src/Talvora.Core/Talvora.Core.csproj" />
  </ItemGroup>
</Project>
