<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Talvora.Abstractions/Talvora.Abstractions.csproj" />
    <ProjectReference Include="../Talvora.Modules.Registry/Talvora.Modules.Registry.csproj" />
  </ItemGroup>
</Project>
